---
title: "Curriculum Vitae"
output: html_document
---

##### <ins>Contact Info</ins> 

Joseph Brandon Gabriel	

Gabrie75@students.rowan.edu	

(908)-514-2202	

##### <ins>EDUCATION</ins>	

**Rowan University | Glassboro, NJ | **                   Anticipated Year of Graduation  2020

Bachelor of Science in Biology
Minor in Chemistry	
	
 **Relevant Coursework**
 
- Chemistry I & II

- Biology I, II, III, IV

- Data Science

- Anatomy & Physiology I

- Organic Chemistry I & 2 
	
	
##### <ins> SKILLS & INTERESTS </ins> 

Technical Skills: 

- Computational data analysis using R
 
- Microsoft Office: Word, Excel, PowerPoint;
 
- Microsoft Windows and Mac OSX operating systems



##### <ins>EXPERIENCE</ins>

**The Dental Family |Westfield, NJ| Shadow Research** 	 June 2019 – August 2019


*  Reviewed and analyzed various dental procedures. 


* Participated in numerous in-depth conversations about dental school and its various requirements. 


* Shadowed the day to day activities of a dentist and studied various dental terminologies used in everyday work.


 **Sitescapes Mason Contractors |Westfield, NJ| Job Manager** 					                     June 2018-August 2018


* Contracted spreadsheets and receipts for various customers


* Supervised various jobs sites to make sure the company was running efficiently and effectively 

* Analyzed and managed jobs sites to mitigate risk to workers


* Monitored progress and controlled any problems that could delay work as they arose


* Scheduled subcontractors and develop criteria needed for subcontractor assignments. 


**Ferraro’s |Westfield, NY| Waiter** 		     May 2016 – August 2016


* Experienced multitasking and how to balance many customers at once in a constantly changing setting


* Gained ethical values in respect to money, receipts and a company’s finances


* Maintained serving standards and followed all regulations while performing duties.

##### <ins> ACTIVITIES </ins>


**Tedx Club |Glassboro, NJ| Senator** 									   September 2019 – Present

 
* Obtains appropriate facilities for organization activities 


* Keeps a record of all members/activities of the organization


* Prepares an agenda with the President for all meetings 


* Prepares organization's calendar of events, and Notifies all members of meetings


* Keeps the organization informed of both organizational and university business 


* Creates and distributes agendas for each meeting of the organization

**Problem Based Learning |Glassboro, NJ| Club Member** 					                September 2018 – Present


* Worked at a pedagogical practice in which students in groups are presented a medical case study each week. 


* Students must use scientific knowledge and advanced reasoning skills in order to determine the disease or syndrome.


* Discussed new problems structures that enabled students to create conceptual models and explain the problem in the presented in the case. 

**Club H.O.P.E |Westfield, NJ| President**  September 2017 – June 2018
 
 
 * Educated club members on various genetic predispositions and volunteered at various nursing homes
 
 
  * reated and organized club meetings, activities, and events
 
 
 * Implemented creative fundraisers to finances the club’s events

**Environmental Work | Westfield, NJ| President**  April 2018- June 2018


 * Restored dilapidated courtyard and built a nesting box for geese


 * Donated furniture and kitchen appliances and bring it to help underprivileged families 
 
 
 * Coordinated afterschool activities to get more people involved  






